version: "3.8"
services:

  db:
    image: mysql
    container_name: db_docker_symfony
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-config/my.cnf:/etc/mysql/my.cnf
    networks:
      - dev

  www:
    build: php
    container_name: www_docker_symfony
    ports:
      - "8000:80"
    volumes:
      - ./php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev
    links:
      - "db:db_docker_symfony"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_docker_symfony
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev
    links:
      - "db:db_docker_symfony"

  maildev:
    image: maildev/maildev
    container_name: maildev_docker_symfony
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - "8081:80"
    restart: always
    networks:
      - dev


networks:
  dev:
    driver: bridge

volumes:
  db-data:
